### ISSUE TITLE
Rgb lcd sourcing 

### ISSUE THREAD

**Issue by NoSkillsToPayTheBillz** [Dean-Chu/Retro-CM3#2]
Can you post a link to Aliexpress or a different site other than AliBaba that had a buy now because I’ve tried to message the seller you showed and they don’t answer at all I can’t source the LCD anywhere so can you find one that will work Without modifying the file because that is really difficult sounding

**Comment by NoSkillsToPayTheBillz** [comment]
I ended up getting them to awnser on Alibaba.com you just have to go to company page and message a different rep they sold me 3 screens for 11 apc and a small shipping fee

**Comment by NoSkillsToPayTheBillz** [comment]
I ended up getting them to awnser on Alibaba.com you just have to go to company page and message a different rep they sold me 3 screens for 11 apc and a small shipping fee

**Comment by NoSkillsToPayTheBillz** [comment]
I ended up getting them to awnser on Alibaba.com you just have to go to company page and message a different rep they sold me 3 screens for 11 apc and a small shipping fee

**Comment by NoSkillsToPayTheBillz** [comment]
I ended up getting them to awnser on Alibaba.com you just have to go to company page and message a different rep they sold me 3 screens for 11 apc and a small shipping fee

**Comment by h3ckman** [comment]
Hey I haven't been able to get a response from the vendor-- would you care to share the part number or link?
